### ISSUE TITLE
[BUG] Wrong Victim Wrong Attacker

### ISSUE THREAD

**Issue by Oyplap** [KarlOfDuty/SCPDiscord#32] opened 2023-01-02 00:42 UTC
**Describe the bug**
OnPlayerHurt event, when a teammate is attacking his teammate, the attacker is the victim and the victim is the attacker. Teamkill logs are the other way around.

**To Reproduce**
1. Enable logs for "OnPlayerHurt: FriendlyFire"
2. Shoot teammate
3. See logs on Discord

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - Version: [3.0.0-Alpha3]
 - API Version: [12.0.0-rc5]

**Comment by KarlOfDuty** [comment] 2023-01-02 00:48
Duplicate of #31

**Closed as completed** 2023-01-02 00:48 UTC
